instructions: |
  Apply the minimal set of labels that accurately characterize the issue/PR:
  - Use at most 1-2 labels unless there's a compelling reason for more
  - Prefer specific labels (bug, feature) over generic ones (question, help wanted)
  - For PRs that fix bugs, use 'bug' not 'enhancement'
  - Never combine: bug + enhancement, feature + enhancement. For these labels, only choose the most relevant one.
  - Reserve 'question' and 'help wanted' for when they're the primary characteristic

labels:
  - bug:
    description: "Something isn't working as expected"
    instructions: |
      Apply when describing or fixing unexpected behavior:
      - Issues: Clear error messages or unexpected outcomes
      - PRs: Fixes for broken functionality
      Don't apply enhancement/feature for bug fixes unless they add significant new functionality
      beyond fixing the bug

  - documentation:
    description: "Improvements or additions to documentation"
    instructions: |
      Apply only when documentation is the primary focus:
      - README updates
      - Code comments and docstrings
      - API documentation
      - Usage examples
      Don't apply for minor doc updates alongside code changes

  - enhancement:
    description: "Improvements to existing features"
    instructions: |
      Apply only for improvements to existing functionality:
      - Performance improvements
      - UI/UX improvements
      - Expanded capabilities of existing features
      Don't apply to:
      - Bug fixes
      - New features
      - Minor tweaks

  - feature:
    description: "New functionality"
    instructions: |
      Apply only for net-new functionality:
      - New API endpoints
      - New commands or tools
      - New user-facing capabilities
      Don't apply to:
      - Improvements to existing features (use enhancement)
      - Bug fixes

  - good first issue:
    description: "Good for newcomers"
    instructions: |
      Apply very selectively to issues that are:
      - Small in scope
      - Well-documented
      - Require minimal context
      - Have clear success criteria
      Don't apply if the task requires significant background knowledge

  - help wanted:
    description: "Extra attention is needed"
    instructions: |
      Apply only when it's the primary characteristic:
      - Issue needs external expertise
      - Current maintainers can't address it
      - Additional contributors would be valuable
      Don't apply just because an issue is open or needs work

  - question:
    description: "Further information is requested"
    instructions: |
      Apply only when the primary purpose is seeking information:
      - Clarification needed before work can begin
      - Architectural discussions
      - Implementation strategy questions
      Don't apply to:
      - Bug reports that need more details
      - Feature requests that need refinement

# These files will be included in the context if they exist
context-files:
  - README.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - .github/ISSUE_TEMPLATE/bug_report.md
  - .github/ISSUE_TEMPLATE/feature_request.md
